language: elixir
sudo: false
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.0
notifications:
  email:
    on_success: change
    on_failure: change
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.3
    - elixir: 1.5
      otp_release: 22.0
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.8
      otp_release: 19.3
jobs:
  include:
    stage: format
    script: mix format --check-formatted
    elixir: 1.8
    otp_release: 22.0
